name: DesireWithAnE
favicon: null
layout_spectrum: 0.52168
typography_spectrum: 0.51997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0d0c'
    - '#f5f5f5'
    - '#dbb051'
    - '#32474a'
    - '#855a30'
  brandStrength: 0.4231282884720713
  lightness: 0.0011593529488891363
  saturation: 0.750119723379612
  rhythmicContrast: 0.25
purpose: []
